// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToKhaiYTe.Models;

namespace ToKhaiYTe.Migrations
{
    [DbContext(typeof(ToKhaiYTeContext))]
    partial class ToKhaiYTeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToKhaiYTe.Models.DauHieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BuonNon")
                        .HasColumnType("bit");

                    b.Property<bool>("DauHong")
                        .HasColumnType("bit");

                    b.Property<bool>("Ho")
                        .HasColumnType("bit");

                    b.Property<bool>("KhoTho")
                        .HasColumnType("bit");

                    b.Property<bool>("NoiBanNgoaiDa")
                        .HasColumnType("bit");

                    b.Property<bool>("Sot")
                        .HasColumnType("bit");

                    b.Property<bool>("TieuChay")
                        .HasColumnType("bit");

                    b.Property<bool>("XuatHuyetNgoaiDa")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DauHieus");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.Days", b =>
                {
                    b.Property<int>("Day")
                        .HasColumnName("day")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.ToTable("days");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("_name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Prefix")
                        .HasColumnName("_prefix")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("ProvinceId")
                        .HasColumnName("_province_id")
                        .HasColumnType("int");

                    b.ToTable("district");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.Gates", b =>
                {
                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.ToTable("gates");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.Months", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Month")
                        .HasColumnName("month")
                        .HasColumnType("int");

                    b.ToTable("months");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.NguoiKhaiBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DauHieuId")
                        .HasColumnType("int");

                    b.Property<int>("GateId")
                        .HasColumnType("int");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoiNhiemId")
                        .HasColumnType("int");

                    b.Property<string>("SoHoChieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThongTinDiChuyenId")
                        .HasColumnType("int");

                    b.Property<int>("ThongTinLienLacId")
                        .HasColumnType("int");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NguoiKhaiBaos");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.PhoiNhiem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DanhsachVacxin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TiepXucDongVat")
                        .HasColumnType("bit");

                    b.Property<bool>("TiepXucNguoiNhiemCovic")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("PhoiNhiems");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.Province", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnName("_code")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("_name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.ToTable("province");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.ThongTinDiChuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<int>("DiaDiemKhoiHanhId")
                        .HasColumnType("int");

                    b.Property<int>("DiaDiemNoiDenId")
                        .HasColumnType("int");

                    b.Property<string>("Khac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthId")
                        .HasColumnType("int");

                    b.Property<bool>("Oto")
                        .HasColumnType("bit");

                    b.Property<string>("SoGhe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoHieuPhuongTien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TauBay")
                        .HasColumnType("bit");

                    b.Property<bool>("TauThuyen")
                        .HasColumnType("bit");

                    b.Property<string>("TrongVong21Ngay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ThongTinDiChuyens");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.ThongTinLienLac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNum")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ThongTinLienLacs");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.Ward", b =>
                {
                    b.Property<int?>("DistrictId")
                        .HasColumnName("_district_id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("_name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Prefix")
                        .HasColumnName("_prefix")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("ProvinceId")
                        .HasColumnName("_province_id")
                        .HasColumnType("int");

                    b.ToTable("ward");
                });

            modelBuilder.Entity("ToKhaiYTe.Models.Years", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Year")
                        .HasColumnName("year")
                        .HasColumnType("int");

                    b.ToTable("years");
                });
#pragma warning restore 612, 618
        }
    }
}
